set_project("super24points")
set_version("2.1.1")
set_languages("cxx20")
set_encodings("utf-8")
if is_os("linux") then
  set_toolchains("mingw")
else
  set_toolchains("msvc")
end
add_rules("mode.debug", "mode.release", "mode.minsizerel")
add_requires("fmt")
target("main")
    add_rules("qt.widgetapp")
    add_packages("fmt")
    add_files("src/*.cpp")
    add_files("src/*.h")
    add_files("src/*.ui")
    add_files("static/static.qrc")
    add_files("lib/dark/darkstyle.qrc")
    add_packages("lib/expected.hpp")
    -- add_includedirs("~/program/qt/6.6.0/gcc_64/")
    -- add_includedirs("/usr/include/qt6/")

target("test")
    set_default(false)
    add_files("test/*.cpp")
    add_packages("lib/expected.hpp")
