set_xmakever("2.1.0")
set_project("super24points")
set_version("2.1.0")
set_languages("cxx20")
set_encodings("utf-8")
add_rules("mode.debug", "mode.release", "mode.minsizerel")
target("super24points")
    add_rules("qt.widgetapp")
    add_files("src/*.cpp")
    add_files("src/*.h")
    add_files("src/*.ui")
    add_files("static/static.qrc")
    add_files("lib/dark/darkstyle.qrc")